apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.endpoint.port }}
      targetPort: 9000
      protocol: TCP
      name: endpoint
    - port: {{ .Values.service.console.port }}
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    {{- include "rustfs.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}-svc
  {{- if eq .Values.ingress.className "traefik" }}
  {{- with .Values.ingress.traefikAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinity.timeoutSeconds }}
  ports:
    - port: {{ .Values.service.endpoint.port }}
      targetPort: {{ .Values.service.endpoint.port }}
      {{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.endpoint.nodePort}}
      {{- end }}
      protocol: TCP
      name: endpoint
    - port: {{ .Values.service.console.port }}
      targetPort: {{ .Values.service.console.port }}
      {{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.console.nodePort}}
      {{- end }}
      protocol: TCP
      name: console
  selector:
    {{- include "rustfs.selectorLabels" . | nindent 6 }}
