apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.endpoint_port }}
      targetPort: 9000
      protocol: TCP
      name: endpoint
    - port: {{ .Values.service.console_port }}
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    app: {{ include "rustfs.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}-svc
  {{- if eq .Values.ingress.className "traefik" }}
  {{- with .Values.ingress.traefikAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinity.timeoutSeconds }}
  ports:
    - port: {{ .Values.service.endpoint_port }}
      targetPort: {{ .Values.service.endpoint_port }}
      protocol: TCP
      name: endpoint
    - port: {{ .Values.service.console_port }}
      targetPort: {{ .Values.service.console_port }}
      protocol: TCP
      name: console
  selector:
    app: {{ include "rustfs.name" . }}
