{{ $dataStorageClassName := .Values.storageclass.data.name }}
{{ $dataStorageSize := .Values.storageclass.data.size }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rustfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.selectorLabels" . | nindent 6 }}
spec:
  serviceName: {{ include "rustfs.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "rustfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rustfs.selectorLabels" . | nindent 6 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 10}}
        {{- end }}
    spec:
      imagePullSecrets: {{ .Values.imagePullSecrets }}
      {{- if .Values.affinity }}
      affinity:
        nodeAffinity:
        {{- if .Values.affinity.nodeAffinity }}
          {{- toYaml .Values.affinity.nodeAffinity | nindent 10 }}
        {{- else }}
          {}
        {{- end }}
        {{- if .Values.affinity.podAntiAffinity.enabled }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "rustfs.name" . }}
              topologyKey: {{ .Values.affinity.podAntiAffinity.topologyKey }}
        {{- end }}
      {{- end }}
      tolerations: {{ .Values.tolerations }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/usr/bin/rustfs"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.endpoint.port }}
              name: endpoint
            - containerPort: {{ .Values.service.console.port }}
              name: console
          envFrom:
            - configMapRef:
                name: {{ include "rustfs.fullname" . }}-config
            - secretRef:
                name: {{ include "rustfs.fullname" . }}-secret
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: logs
              mountPath: {{ .Values.config.rustfs.obs_log_directory }}
            {{- range $i := until (int .Values.dataVolumeCount) }}
            - name: rustfs-data-{{ $i }}
              mountPath: /data-{{ $i }}
            {{- end }}
      volumes:
          {{- if not .Values.storageclass.logs }}
        - name: logs
          emptyDir: {}
          {{- end}}
        - name: tmp
          emptyDir: 
            medium: Memory
  volumeClaimTemplates:
    {{- range $i := until (int .Values.dataVolumeCount) }}
    - metadata:
        name: rustfs-data-{{ $i }}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ $dataStorageClassName }}
        resources:
          requests:
            storage: {{ $dataStorageSize }}
    {{- end }}
    {{- if .Values.storageclass.logs }}
    - metadata:
        name: logs
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storageclass.logs.name }}
        resources:
          requests:
            storage: {{ .Values.storageclass.logs.size }}
    {{- end}}